pool:
  vmImage: 'Ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: 14
- script: |
    set -o errexit -o pipefail
    npm ci
    npm run check
    npm run test
    npm run build
    npm pack
  displayName: 'Build and pack'
