name: 'Docs: Create bundle'

# If this project has docs, set a correct bundle-name below (and also
# in the other workflows) and uncomment the pull_request trigger.

on:
    # pull_request:
    #     types: [synchronize, opened, reopened]
    #     paths:
    #         - .github/workflows/docs-bundle.yml
    #         - doc
    workflow_dispatch:
    workflow_call:

jobs:
    create-doc-bundle:
        uses: NordicSemiconductor/pc-nrfconnect-shared/.github/workflows/docs-bundle.yml@main
        with:
            bundle-name: nrf-connect-boilerplate
